{% set version = "1.2.1" %}

package:
  name: redis-entraid
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/redis-entraid/redis_entraid-{{ version }}.tar.gz
  sha256: a7c479ce46e6edb35bce9dd804d1cad7be99a3330815cfe028a648b486a10b41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - redis-py >=5.3.0
    - pyjwt >=2.12.0,<2.13.dev0
    - msal >=1.33.0,<1.34.dev0
    - azure-identity >=1.24.0,<1.25.dev0

test:
  imports:
    - redis_entraid
  commands:
    - pip check
  requires:
    - pip
    - python >={{ python_min }}

about:
  home: https://pypi.org/project/redis-entraid/
  summary: Entra ID credentials provider implementation for Redis-py client
  dev_url: https://github.com/redis/redis-py-entraid/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ibhagwat-upland
